export const projects = [
  {
    id: "todo-app",
    name: "Todo App",
    description: "A simple todo app built with react and styled-components.",
    codeURL: "https://github.com/zun-liang/todo-app",
    femURL: "",
    liveURL: "https://zun-liang.github.io/todo-app/",
    srcLight:
      "https://raw.githubusercontent.com/zun-liang/todo-app/master/public/screenshots/screenshot-desktop-light.png",
    srcDark:
      "https://raw.githubusercontent.com/zun-liang/todo-app/master/public/screenshots/screenshot-desktop-dark.png",
    introduction:
      "This solo project is the solution to Frontend Mentor Challenge Todo App.",
    functions: [
      "View the optimal layout for the app depending on their device's screen size",
      "See hover states for all interactive elements on the page",
      "Add new todos to the list",
      "Mark todos as complete",
      "Delete todos from the list",
      "Filter by all/active/complete todos",
      "Clear all completed todos",
      "Toggle light and dark mode",
      "Drag and drop to reorder items on the list",
    ],
    tools: [
      "HTML",
      "CSS",
      "Javascript",
      "React",
      "Styled-Components",
      "Vite",
      "NanoID",
      "React Beautiful DND",
      "@hello-pangea/dnd",
    ],
    purpose:
      "My main purpose of doing this project is to pratice working with localStorage. At the time of doing this project, I haven't learned how to store data except for saving them in localStorage/sessionStorage.",
    spotlight: "spotlight paragraph goes here...",
    learned:
      " In this project, I especially learned how to use NanoID to generate React map keys and how to use React Beautiful DND. I used to think that NanoID can only generate random IDs which is not helpful for generating React map keys. However, I found that if I use NanoID to generate to do item's id and use its id as key, then it works perfectly. Moreover, the original React Beautiful DND is no longer maintaned...",
    resources: [],
  },
  {
    id: "portfolio",
    name: "Portfolio",
    description: "Secret blog management in my portfolio.",
    codeURL: "https://github.com/zun-liang/zun-liang.github.io",
    femURL: null,
    liveURL: "https://zun-liang.github.io/",
    srcLight: "../src/assets/images/screenshots/screenshot-desktop-light.png",
    srcDark: "../src/assets/images/screenshots/screenshot-desktop-dark.png",
    introduction: "",
    functions: [],
    tools: [],
    purpose: "",
    spotlight: "",
    learned: "",
    resources: "",
  },
];
